export const RESERVE = "RESERVE";
export const RESERVE_TITLE = "RESERVE_TITLE";
export const RESERVE_CONTEXT = "RESERVE_CONTEXT";
export const RESERVE_SURE = "RESERVE_SURE";
export const DRAFT = "DRAFT";
export const CHECK = "CHECK";
export const MANAGE = "MANAGE";
export const MANAGE_ADD_ADMIN = "MANAGE_ADD_ADMIN";
export const MANAGE_ADD_STAFF = "MANAGE_ADD_STAFF";
export const MANAGE_REMOVE_PERSON = "MANAGE_REMOVE_PERSON";
export const MANAGE_EDIT_RESERVATION_SHOW = "MANAGE_EDIT_RESERVATION_SHOW";
export const MANAGE_EDIT_RESERVATION = "MANAGE_EDIT_RESERVATION";
export const FSM = "FSM";

export default {
    CHECK: CHECK,
    MANAGE: MANAGE,
    MANAGE_ADD_ADMIN: MANAGE_ADD_ADMIN,
    MANAGE_ADD_STAFF: MANAGE_ADD_STAFF,
    MANAGE_REMOVE_PERSON: MANAGE_REMOVE_PERSON,
    MANAGE_EDIT_RESERVATION_SHOW: MANAGE_EDIT_RESERVATION_SHOW,
    MANAGE_EDIT_RESERVATION: MANAGE_EDIT_RESERVATION,
    RESERVE: RESERVE,
    RESERVE_TITLE: RESERVE_TITLE,
    RESERVE_CONTEXT: RESERVE_CONTEXT,
    RESERVE_SURE: RESERVE_SURE,
    DRAFT: DRAFT,
    FSM : FSM,
}